//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FileSearchProject2Entities : DbContext
    {
        public FileSearchProject2Entities()
            : base("name=FileSearchProject2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DateSearch> DateSearches { get; set; }
        public virtual DbSet<DuplicateSearch> DuplicateSearches { get; set; }
        public virtual DbSet<History> Histories { get; set; }
        public virtual DbSet<NameSearch> NameSearches { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
